### ISSUE TITLE
/gokrazy/ntp: permission denied

### ISSUE THREAD

**Issue by Syphdias** [gokrazy/gokrazy#205] opened 2023-07-13 13:03 UTC
## Platform
I’m using: gokrazy/rpi4b

## Observed behavior
Apparently ntp does not work. And is stuck in restarting.
```
1970/01/01 01:00:10 gokrazy: attempt 9, starting ["/gokrazy/ntp"]
1970/01/01 01:00:10 privdrop.go:85: fork/exec /gokrazy/ntp: permission denied
1970/01/01 01:00:10 gokrazy: exit status 1
1970/01/01 01:00:11 gokrazy: attempt 10, starting ["/gokrazy/ntp"]
1970/01/01 01:00:11 privdrop.go:85: fork/exec /gokrazy/ntp: permission denied
1970/01/01 01:00:11 gokrazy: exit status 1
1970/01/01 01:00:12 gokrazy: attempt 11, starting ["/gokrazy/ntp"]
1970/01/01 01:00:12 privdrop.go:85: fork/exec /gokrazy/ntp: permission denied
1970/01/01 01:00:12 gokrazy: exit status 1
```

## Expected behavior
ntp to work

## What I tried to fix it
I tried to start over:
```
sudo wipefs -a /dev/sde
sudo dd if=/dev/zero of=/dev/sde bs=4M status=progress
sync
# replug SD card
gok -i gokrazy overwrite --full /dev/sde
```

**Comment by christian-heusel** [comment] 2023-07-13 13:32
So I also started from a clean SD card but cannot reproduce the issue 🤔

**Comment by Syphdias** [comment] 2023-07-13 14:09
I'm pretty sure there is something I am doing wrong. Or maybe it is a hardware issue. Both RPi Model B 4GB and SD card (SanDisk Extreme microSDXC UHS-I memory card 128 GB) are new. Maybe I bought the wrong SD format?
I did not consider it being a network issue. I don't think I block anything outgoing.
Everything(\*) else seems to work so far.

I might be able to try another SD card but I  don't have a spare RPi laying around (took long enough to get this one).

In case I did something wrong in the config:
```
❯ cat ~/gokrazy/gokrazy/config.json
{
    "Hostname": "gokrazy",
    "Update": {
        "HTTPPassword": "XXXXXXXXXXXXXXX"
    },
    "Packages": [
        "github.com/gokrazy/fbstatus",
        "github.com/gokrazy/hello",
        "github.com/gokrazy/serial-busybox",
        "github.com/gokrazy/breakglass",
        "github.com/gokrazy/iptables",
        "github.com/gokrazy/nsenter",
        "github.com/gokrazy/podman",
        "github.com/greenpau/cni-plugins/cmd/cni-nftables-portmap",
        "github.com/greenpau/cni-plugins/cmd/cni-nftables-firewall",
        "github.com/gokrazy/wifi",
        "github.com/gokrazy/mkfs"
    ],
    "PackageConfig": {
        "github.com/gokrazy/breakglass": {
            "CommandLineFlags": [
                "-authorized_keys=/etc/breakglass.authorized_keys"
            ],
            "ExtraFilePaths": {
                "/etc/breakglass.authorized_keys": "/home/syphdias/gokrazy/gokrazy/breakglass.authorized_keys"
            }
        },
        "github.com/gokrazy/gokrazy/cmd/randomd": {
            "ExtraFileContents": {
                "/etc/machine-id": "1bfe4ba3d20668c4608cd4585f9bf6e1\n"
            }
        },
        "github.com/gokrazy/wifi": {
            "ExtraFilePaths": {
                "/etc/wifi.json": "wifi.json"
            }
        }
    },
    "SerialConsole": "disabled",
    "InternalCompatibilityFlags": {}
}
```


(\*) Since the time is off, this prevents stuff like pulling docker images or anything that requires certificates I assume. fbstatus was restarting until I connected a monitor (will probably remove this package together with hello). And iptables which I added in preparation for podman. I also tried without iptables, nsenter, podman, and cni packages. No change.

**Comment by Syphdias** [comment] 2023-07-13 14:44
Unfortunately, I don't have a spare MicroSD card, only a big one :/

**Comment by stapelberg** [comment] 2023-07-13 14:52
This is really strange. I don’t think it’s a hardware or SD card issue. And it shouldn’t be possible to configure things wrong in this regard — NTP is expected to always work.

Are you by any chance on an extremely old kernel version for some reason? Can you share a screenshot of the web interface?

What does `gok sbom` print for your instance? 

What’s the output of `gok overwrite --root /tmp/root.squashfs` and `unsquashfs -ll /tmp/root.squashfs`?

**Comment by Syphdias** [comment] 2023-07-13 15:16
I continued to try some stuff and updated the running system a few times. So here is the current config is:
```
{
    "Hostname": "gokrazy",
    "Update": {
        "HTTPPassword": "XXXXXXXXXXXXXXX"
    },
    "Packages": [
        "github.com/gokrazy/serial-busybox",
        "github.com/gokrazy/breakglass",
        "github.com/gokrazy/wifi",
        "github.com/restic/rest-server"
    ],
    "PackageConfig": {
        "github.com/gokrazy/breakglass": {
            "CommandLineFlags": [
                "-authorized_keys=/etc/breakglass.authorized_keys"
            ],
            "ExtraFilePaths": {
                "/etc/breakglass.authorized_keys": "/home/syphdias/gokrazy/gokrazy/breakglass.authorized_keys"
            }
        },
        "github.com/gokrazy/gokrazy/cmd/randomd": {
            "ExtraFileContents": {
                "/etc/machine-id": "1bfe4ba3d20668c4608cd4585f9bf6e1\n"
            }
        },
        "github.com/gokrazy/wifi": {
            "ExtraFilePaths": {
                "/etc/wifi.json": "wifi.json"
            }
        }
    },
    "SerialConsole": "disabled",
    "InternalCompatibilityFlags": {}
}
```

> I have no clue, but what are the permissions of the ntp executable?

Interesting, mine does not have read and execution permissions for other. 
```
/tmp/breakglass2664188945 # ls -l /gokrazy/ntp 
-rwxr-x---    1 0        0          3077622 Jul 13  2023 /gokrazy/ntp
/tmp/breakglass2664188945 # sha256sum /gokrazy/ntp
abd55dff3cffffc8287772c1e20236a75115416bd24cc86edf99f5019fc11a0d  /gokrazy/ntp
```

> What does gok sbom print for your instance?
```
❯ gok -i gokrazy sbom
{
    "sbom_hash": "9f397af99732fe4f01f1926eeccf9f1cd1e5a18d7c75804b4d6e6ea92a5b7aeb",
    "sbom": {
        "config_hash": {
            "path": "/home/syphdias/gokrazy/gokrazy/config.json",
            "hash": "ee555a1fe1f92fcb70e17d1fa1f30d63c004e3c788528c2cf7d9bd24d9b3d867"
        },
        "go_mod_hashes": [
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/breakglass/go.mod",
                "hash": "d6c65c121d526e8a300bf3ec371aa7cc6935791d00da3d991e522e0f96a46561"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/firmware/go.mod",
                "hash": "82c5ded2f2ef53cba241fcb063fccb1fc67b0c2e48caf925424544aac5737e45"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/gokrazy/cmd/dhcp/go.mod",
                "hash": "380f8e6e53758be67d27a3f9496418cdb2b1b945debe80a62b44a83b267b5905"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/gokrazy/cmd/heartbeat/go.mod",
                "hash": "380f8e6e53758be67d27a3f9496418cdb2b1b945debe80a62b44a83b267b5905"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/gokrazy/cmd/ntp/go.mod",
                "hash": "380f8e6e53758be67d27a3f9496418cdb2b1b945debe80a62b44a83b267b5905"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/gokrazy/cmd/randomd/go.mod",
                "hash": "380f8e6e53758be67d27a3f9496418cdb2b1b945debe80a62b44a83b267b5905"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/gokrazy/go.mod",
                "hash": "380f8e6e53758be67d27a3f9496418cdb2b1b945debe80a62b44a83b267b5905"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/kernel/go.mod",
                "hash": "04712498c2cb49bdb55ee226194f059ee6d88f36dfffdb4d2efdd135217ff75d"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/rpi-eeprom/go.mod",
                "hash": "402ac10af813febbc4fb62b7e8bcbb13c90fb38c19c93975fc75065583697b71"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/serial-busybox/go.mod",
                "hash": "272c4fdfe09f37065e0a49ba8e8d4815413f13f2a3e04396cb80dd1882fb9885"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/builddir/github.com/gokrazy/wifi/go.mod",
                "hash": "e4b7fcc33f3fe7322273c09698bf7cb7b47dddaa60ee1a233f4d8499b8401491"
            }
        ],
        "extra_file_hashes": [
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43430-sdio.bin",
                "hash": "93f3c40c94340c29a40714cb04e3e89974870fcae42a844b8a4544750159f40d"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43430-sdio.clm_blob",
                "hash": "3376b9c9b32d16bf762e21c7fafb665365070ae240d092498d0d1987c22022aa"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43430-sdio.raspberrypi,3-model-b.txt",
                "hash": "489c12a33e0fd0899cd27bfb316b30944f0b9dd571c266a0aa3704b35817b788"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43430-sdio.raspberrypi,model-zero-2-w.txt",
                "hash": "489c12a33e0fd0899cd27bfb316b30944f0b9dd571c266a0aa3704b35817b788"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43430-sdio.raspberrypi,model-zero-w.txt",
                "hash": "fc3949a4c32f07c18308e7e145c7615be314158e7d714a80e04e4791f16495f9"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43430b0-sdio.clm_blob",
                "hash": "fce7cbb62ffa6a5a65ca97b13f6fbf28d06c02d986c2072d65bf72164755fc34"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43430b0-sdio.raspberrypi,model-zero-2-w.bin",
                "hash": "510a7dd1e056199b309425548ee0bd846993a1837ac7fa1e4d3e641f05a1327a"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43430b0-sdio.raspberrypi,model-zero-2-w.txt",
                "hash": "67b0e325bf76d096ce06044d2a442b95626f274096ce5724daaa8bcdd179b599"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43455-sdio.bin",
                "hash": "97676e8e2630ff9e4ce4fdfc5ccf59b9ccfcd601f04b20ec4e46dd4b094e09fc"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43455-sdio.clm_blob",
                "hash": "8e2250518bc789e53109728c3c0a6124bc3801a75a1cb4966125753cf1f0252e"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,3-model-a-plus.txt",
                "hash": "ae2f9e43c609766036cd7d82d709e62135fc266cbe8f40fb10f782114d585658"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,3-model-b-plus.txt",
                "hash": "ae2f9e43c609766036cd7d82d709e62135fc266cbe8f40fb10f782114d585658"
            },
            {
                "path": "/home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles/lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,4-model-b.txt",
                "hash": "edb6f4e4fb19e18940004124feb4ffe160d72fc607243a07a4480338a28b2748"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/breakglass.authorized_keys",
                "hash": "1895fe07a76266c50fdea4946b788981498302e8984cc8e079b4bf1715d86609"
            },
            {
                "path": "/home/syphdias/gokrazy/gokrazy/wifi.json",
                "hash": "paranoia"
            }
        ]
    }
}
```

> What’s the output of gok overwrite --root /tmp/root.squashfs and unsquashfs -ll /tmp/root.squashfs?

```
❯ gok -i gokrazy overwrite --root /tmp/root.squashfs
gokrazy gok g56839a on GOARCH=amd64 GOOS=linux

Build target: CGO_ENABLED=0 GOARCH=arm64 GOOS=linux
Build timestamp: 2023-07-13T17:14:27+02:00
Loading system CA certificates from /etc/ssl/certs/ca-certificates.crt
Building 3 Go packages:

  github.com/gokrazy/serial-busybox

  github.com/gokrazy/breakglass
    will be started with command-line flags
      from /home/syphdias/gokrazy/gokrazy/config.json
      last modified: 2023-07-13T17:08:32+02:00 (5m55s ago)

  github.com/gokrazy/wifi

[done] in 1.17s                        

Including extra files for Go packages:

  github.com/gokrazy/breakglass
    will include extra files in the root file system
      from /home/syphdias/gokrazy/gokrazy/breakglass.authorized_keys
      last modified: 2023-07-13T12:49:43+02:00 (4h24m45s ago)

  github.com/gokrazy/wifi
    will include extra files in the root file system
      from wifi.json
      last modified: 2023-07-13T17:04:52+02:00 (9m36s ago)
    will include extra files in the root file system
      from /home/syphdias/go/pkg/mod/github.com/gokrazy/wifi@v0.0.0-20230315194431-f611656338b6/_gokrazy/extrafiles
      last modified: 2023-07-13T10:37:37+02:00 (6h36m51s ago)

Including loadable kernel modules from:
/home/syphdias/go/pkg/mod/github.com/gokrazy/kernel@v0.0.0-20230712041245-e563d7441232/lib/modules

Feature summary:
  use GPT: true
  use PARTUUID: true
  use GPT PARTUUID: true

Creating root file system
[done] in 0.64s                           

Build complete!

To interact with the device, gokrazy provides a web interface reachable at:

	http://gokrazy:XXXXXXXXXX@gokrazy/

In addition, the following Linux consoles are set up:

	1. foreground Linux framebuffer console on HDMI

❯ unsquashfs -ll /tmp/root.squashfs
dr-xr-xr-x root/root               143 2023-07-13 17:14 squashfs-root
dr-xr-xr-x root/root                 3 2023-07-13 17:14 squashfs-root/dev
dr-xr-xr-x root/root               237 2023-07-13 17:14 squashfs-root/etc
-rw------- root/root                81 2023-07-13 12:49 squashfs-root/etc/breakglass.authorized_keys
-r-------- root/root                20 2023-07-13 17:14 squashfs-root/etc/gokr-pw.txt
dr-xr-xr-x root/root                32 2023-07-13 17:14 squashfs-root/etc/gokrazy
-r--r--r-- root/root              7286 2023-07-13 17:14 squashfs-root/etc/gokrazy/sbom.json
-r--r--r-- root/root                 7 2023-07-13 17:14 squashfs-root/etc/hostname
-r--r--r-- root/root                34 2023-07-13 17:14 squashfs-root/etc/hosts
-r--r--r-- root/root                 2 2023-07-13 17:14 squashfs-root/etc/http-port.txt
-r--r--r-- root/root                 3 2023-07-13 17:14 squashfs-root/etc/https-port.txt
-rw-r--r-- root/root              2298 2023-05-15 21:50 squashfs-root/etc/localtime
-r--r--r-- root/root                33 2023-07-13 17:14 squashfs-root/etc/machine-id
lr--r--r-- root/root                16 2023-07-13 17:14 squashfs-root/etc/resolv.conf -> /tmp/resolv.conf
dr-xr-xr-x root/root                36 2023-07-13 17:14 squashfs-root/etc/ssl
-r--r--r-- root/root            220831 2023-07-13 17:14 squashfs-root/etc/ssl/ca-bundle.pem
-rw-r----- root/root                72 2023-07-13 17:04 squashfs-root/etc/wifi.json
dr-xr-xr-x root/root                82 2023-07-13 17:14 squashfs-root/gokrazy
-rwxr-x--- root/root           5127027 2023-07-13 17:14 squashfs-root/gokrazy/dhcp
-rwxr-x--- root/root           8099164 2023-07-13 17:14 squashfs-root/gokrazy/heartbeat
-rwxr-x--- root/root          11021235 2023-07-13 17:14 squashfs-root/gokrazy/init
-rwxr-x--- root/root           3077622 2023-07-13 17:14 squashfs-root/gokrazy/ntp
-rwxr-x--- root/root           2190896 2023-07-13 17:14 squashfs-root/gokrazy/randomd
dr-xr-xr-x root/root                46 2023-07-13 17:14 squashfs-root/lib
dr-xr-xr-x root/root                27 2023-07-13 17:14 squashfs-root/lib/firmware
dr-xr-xr-x root/root               630 2023-07-13 17:14 squashfs-root/lib/firmware/brcm
-r--r----- root/root            419798 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43430-sdio.bin
-r--r----- root/root              4733 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43430-sdio.clm_blob
-r--r----- root/root               874 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43430-sdio.raspberrypi,3-model-b.txt
-r--r----- root/root               874 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43430-sdio.raspberrypi,model-zero-2-w.txt
-r--r----- root/root              1121 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43430-sdio.raspberrypi,model-zero-w.txt
-r--r----- root/root             11209 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43430b0-sdio.clm_blob
-r--r----- root/root            416101 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43430b0-sdio.raspberrypi,model-zero-2-w.bin
-r--r----- root/root              1613 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43430b0-sdio.raspberrypi,model-zero-2-w.txt
-r--r----- root/root            624943 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43455-sdio.bin
-r--r----- root/root             14036 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43455-sdio.clm_blob
-r--r----- root/root              1884 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,3-model-a-plus.txt
-r--r----- root/root              1884 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,3-model-b-plus.txt
-r--r----- root/root              1883 2023-07-13 10:37 squashfs-root/lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,4-model-b.txt
dr-xr-xr-x root/root                28 2023-07-13 17:14 squashfs-root/lib/modules
dr-xr-xr-x root/root               315 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3
dr-xr-xr-x root/root                55 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel
dr-xr-xr-x root/root                67 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/crypto
-r--r----- root/root             94088 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/crypto/cmac.ko
-r--r----- root/root            181504 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/crypto/ecc.ko
-r--r----- root/root            124984 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/crypto/ecdh_generic.ko
dr-xr-xr-x root/root                56 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers
dr-xr-xr-x root/root                86 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/bluetooth
-r--r----- root/root            151856 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/bluetooth/btbcm.ko
-r--r----- root/root            158432 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/bluetooth/btqca.ko
-r--r----- root/root            116672 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/bluetooth/btqcomsmd.ko
-r--r----- root/root            649000 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/bluetooth/hci_uart.ko
dr-xr-xr-x root/root                40 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/media
dr-xr-xr-x root/root                46 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/media/common
-r--r----- root/root             74904 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/media/common/uvc.ko
dr-xr-xr-x root/root               122 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/media/common/videobuf2
-r--r----- root/root            339104 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/media/common/videobuf2/videobuf2-common.ko
-r--r----- root/root            102232 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/media/common/videobuf2/videobuf2-memops.ko
-r--r----- root/root            184768 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/media/common/videobuf2/videobuf2-v4l2.ko
-r--r----- root/root            125264 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/media/common/videobuf2/videobuf2-vmalloc.ko
dr-xr-xr-x root/root                26 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/media/usb
dr-xr-xr-x root/root                34 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/media/usb/uvc
-r--r----- root/root           1211200 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/media/usb/uvc/uvcvideo.ko
dr-xr-xr-x root/root                31 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/net
dr-xr-xr-x root/root                31 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless
dr-xr-xr-x root/root                32 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom
dr-xr-xr-x root/root                47 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211
dr-xr-xr-x root/root                67 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac
dr-xr-xr-x root/root                38 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/bca
-r--r----- root/root            148648 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/bca/brcmfmac-bca.ko
-r--r----- root/root           2497408 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/brcmfmac.ko
dr-xr-xr-x root/root                38 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/cyw
-r--r----- root/root            148648 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/cyw/brcmfmac-cyw.ko
dr-xr-xr-x root/root                38 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/wcc
-r--r----- root/root            148648 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/wcc/brcmfmac-wcc.ko
dr-xr-xr-x root/root                34 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211/brcmutil
-r--r----- root/root            156560 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/drivers/net/wireless/broadcom/brcm80211/brcmutil/brcmutil.ko
dr-xr-xr-x root/root                32 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/net
dr-xr-xr-x root/root                35 2023-07-13 17:14 squashfs-root/lib/modules/6.4.3/kernel/net/bluetooth
-r--r----- root/root           6588800 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/kernel/net/bluetooth/bluetooth.ko
-r--r----- root/root             11540 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.alias
-r--r----- root/root             11609 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.alias.bin
-r--r----- root/root             58511 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.builtin
-r--r----- root/root             62220 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.builtin.bin
-r--r----- root/root            322080 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.builtin.modinfo
-r--r----- root/root              2394 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.dep
-r--r----- root/root              3405 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.dep.bin
-r--r----- root/root                 0 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.devname
-r--r----- root/root               921 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.order
-r--r----- root/root                55 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.softdep
-r--r----- root/root              8800 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.symbols
-r--r----- root/root             11374 2023-07-13 10:31 squashfs-root/lib/modules/6.4.3/modules.symbols.bin
dr-xr-xr-x root/root                 3 2023-07-13 17:14 squashfs-root/perm
dr-xr-xr-x root/root                 3 2023-07-13 17:14 squashfs-root/proc
dr-xr-xr-x root/root                 3 2023-07-13 17:14 squashfs-root/run
dr-xr-xr-x root/root                 3 2023-07-13 17:14 squashfs-root/sys
dr-xr-xr-x root/root                 3 2023-07-13 17:14 squashfs-root/tmp
dr-xr-xr-x root/root                67 2023-07-13 17:14 squashfs-root/user
-rwxr-x--- root/root           9387953 2023-07-13 17:14 squashfs-root/user/breakglass
-rwxr-x--- root/root           6264042 2023-07-13 17:14 squashfs-root/user/serial-busybox
-rwxr-x--- root/root           5716337 2023-07-13 17:14 squashfs-root/user/wifi
dr-xr-xr-x root/root                 3 2023-07-13 17:14 squashfs-root/var
```

**Comment by stapelberg** [comment] 2023-07-13 15:47
Oh! I think it’s your umask setting. Try running `umask 0022` before running `gok`. I’ll try and submit a fix for this.

**Comment by Syphdias** [comment] 2023-07-13 15:47
@christian-heusel thanks for the hin.
I usually run umask of `0027`. I set it to 0022 and then ran `gok upgrade`. This fixed it

**Comment by Syphdias** [comment] 2023-07-13 15:48
@stapelberg Yes, exactly it. I just found out.

**Comment by stapelberg** [comment] 2023-07-13 16:07
Should be fixed now if you update your gok cli from https://github.com/gokrazy/tools

**Closed** 2023-07-13 16:06 UTC

**Comment by Syphdias** [comment] 2023-07-13 18:21
I can confirm this fixes it. Thank you!
