### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by XenGi** [gokrazy/gokrazy#30] opened 2017-06-26 22:44 UTC
OS: Archlinux (4.11.6-1-ck-broadwell)
Go: 1.8.3

```
$ go env                                                                                                                               
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xengi/.go/"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build826494141=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

Trying to follow the quickstart guide:

```
$ go get -u github.com/gokrazy/tools/cmd/gokr-packer
$ sudo setcap CAP_SYS_ADMIN,CAP_DAC_OVERRIDE=ep $(go env GOPATH)/bin/gokr-packer
$ gokr-packer -overwrite=/dev/mmcblk0 github.com/gokrazy/hello
2017/06/27 00:41:23 packer.go:213: installing [github.com/gokrazy/hello]
go install runtime/internal/sys: mkdir /usr/lib/go/pkg/linux_arm64: permission denied
2017/06/27 00:41:23 packer.go:458: exit status 1
```

The problem is that it tries to use `go install` which tries to put stuff in `$GOROOT` which it shouldn't do. Instead it should use `go build` and put stuff into `$GOPATH`. At least that is what I think is right. I'm pretty new in the go world.

**Comment by stapelberg** [comment] 2017-06-27 07:09
Thanks for the report! This issue is a duplicate of #23

**Closed by stapelberg** 2017-06-27 07:09 UTC
